# Default values for replicated-starter-kots.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# https://github.com/replicatedhq/helm-charts/blob/main/charts/replicated-library/values.yaml

apps:
  ghost:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      ghost:
        image:
          repository: docker.io/bitnami/ghost
          tag: "5"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
            targetPort: 2368
        env:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          ALLOW_EMPTY_PASSWORD: yes
          GHOST_DATABASE_HOST: mysql
          GHOST_DATABASE_PORT_NUMBER: 3306
          GHOST_DATABASE_USER: bn_ghost
          GHOST_DATABASE_NAME: bitnami_ghost

# ghost:
#     image: docker.io/bitnami/ghost:5
#     ports:
#       - '80:2368'
#     volumes:
#       - 'ghost_data:/bitnami/ghost'
#     depends_on:
#       - mysql
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#       - GHOST_DATABASE_HOST=mysql
#       - GHOST_DATABASE_PORT_NUMBER=3306
#       - GHOST_DATABASE_USER=bn_ghost
#       - GHOST_DATABASE_NAME=bitnami_ghost


# global:
#   labels: {}
#   annotations: {}

# apps:
#   vaultwarden:
#     enabled: true
#     type: deployment
#     replicas: 1
#     containers:
#       vaultwarden:
#         image:
#           repository: vaultwarden/server
#           tag: 1.27.0-alpine
#         volumeMounts:
#         - mountPath: /data
#           name: vaultwarden
#     volumes:
#     - name: vaultwarden
#       persistentVolumeClaim:
#         claimName: vaultwarden

# services:
#   vaultwarden:
#     enabled: true
#     appName: vaultwarden
#     type: ClusterIP
#     ports:
#       http:
#         enabled: true
#         port: 8080
#         protocol: HTTP
#         targetPort: 80

# ingresses:
#   vaultwarden:
#     enabled: true
#     serviceName: vaultwarden
#     hosts:
#       - host: vaultwarden.example.com
#         paths:
#           - path: /
#             pathType: Prefix
#             service:
#               port: 8080
#     tls:
#     - hosts:
#         - vaultwarden.example.com
#       secretName: vaultwarden-tls-secret

# persistence:
#   vaultwarden:
#     enabled: true
#     type: persistentVolumeClaim
#     persistentVolumeClaim:
#       spec:
#         accessModes:
#           - ReadWriteOnce
#         resources:
#           requests:
#             storage: 100Mi
